-- MySQL Script generated by MySQL Workbench
-- Fri Aug  9 11:10:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dice_game
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dice_game` ;

-- -----------------------------------------------------
-- Schema dice_game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dice_game` DEFAULT CHARACTER SET utf8 ;
USE `dice_game` ;

-- -----------------------------------------------------
-- Table `dice_game`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dice_game`.`players` ;

CREATE TABLE IF NOT EXISTS `dice_game`.`players` (
  `id_players` BINARY(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `reg_date` DATE NOT NULL,
  PRIMARY KEY (`id_players`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dice_game`.`dice_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dice_game`.`dice_games` ;

CREATE TABLE IF NOT EXISTS `dice_game`.`dice_games` (
  `id_games` BINARY(16) NOT NULL,
  `is_winner` TINYINT(1) NOT NULL DEFAULT 0,
  `is_anonim` TINYINT(1) NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `players_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_games`),
  INDEX `fk_dice_games_players_idx` (`players_id` ASC) ,
  CONSTRAINT `fk_dice_games_players`
    FOREIGN KEY (`players_id`)
    REFERENCES `dice_game`.`players` (`id_players`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dice_game`.`dice_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dice_game`.`dice_results` ;

CREATE TABLE IF NOT EXISTS `dice_game`.`dice_results` (
  `id_results` BINARY(16) NOT NULL,
  `id_dice` INT NOT NULL,
  `result` INT NOT NULL,
  `dice_games_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_results`),
  INDEX `fk_dice_results_dice_games1_idx` (`dice_games_id` ASC) ,
  CONSTRAINT `fk_dice_results_dice_games1`
    FOREIGN KEY (`dice_games_id`)
    REFERENCES `dice_game`.`dice_games` (`id_games`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
