-- MySQL Script generated by MySQL Workbench
-- Fri Jul 26 07:58:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dice_game
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dice_game` ;

-- -----------------------------------------------------
-- Schema dice_game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dice_game` DEFAULT CHARACTER SET utf8 ;
USE `dice_game` ;

-- -----------------------------------------------------
-- Table `dice_game`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dice_game`.`players` ;

CREATE TABLE IF NOT EXISTS `dice_game`.`players` (
  `idplayers` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `reg_date` DATE NOT NULL,
  PRIMARY KEY (`idplayers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dice_game`.`dice_rolls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dice_game`.`dice_rolls` ;

CREATE TABLE IF NOT EXISTS `dice_game`.`dice_rolls` (
  `id_roll` INT NOT NULL,
  `players_idplayers` INT NOT NULL,
  `is_winner` TINYINT(1) NOT NULL DEFAULT 0,
  `is_anonim` TINYINT(1) NOT NULL DEFAULT 1,
  INDEX `fk_dice_rolls_players_idx` (`players_idplayers` ASC) ,
  PRIMARY KEY (`id_roll`),
  CONSTRAINT `fk_dice_rolls_players`
    FOREIGN KEY (`players_idplayers`)
    REFERENCES `dice_game`.`players` (`idplayers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dice_game`.`dice_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dice_game`.`dice_results` ;

CREATE TABLE IF NOT EXISTS `dice_game`.`dice_results` (
  `id_dice` INT NOT NULL,
  `roll_result` INT NOT NULL,
  `dice_rolls_id_roll` INT NOT NULL,
  INDEX `fk_dice_results_dice_rolls1_idx` (`dice_rolls_id_roll` ASC) ,
  PRIMARY KEY (`id_dice`, `dice_rolls_id_roll`),
  CONSTRAINT `fk_dice_results_dice_rolls1`
    FOREIGN KEY (`dice_rolls_id_roll`)
    REFERENCES `dice_game`.`dice_rolls` (`id_roll`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
